name: Security Scan

on:
  pull_request:
    branches: [ main, develop, "release/*" ]
  push:
    branches: [ main, develop, "release/*" ]
  schedule:
    # Run weekly security scans on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_call:  # Allow this workflow to be called by other workflows

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install safety bandit[toml]

    - name: Run Safety check for known vulnerabilities
      run: |
        # Check installed packages for known security vulnerabilities
        safety check --json --output safety-report.json || true

        # Also check requirements files
        safety check -r requirements.txt -r requirements-dev.txt --json --output safety-requirements.json || true

    - name: Run Bandit security linter
      run: |
        # Scan source code for common security issues
        bandit -r src/ -f json -o bandit-report.json || true
        bandit -r src/ --format=txt

    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          safety-requirements.json
          bandit-report.json
        retention-days: 30
